### PR TITLE
Update ApplicationInsights.config documentation

### PR DESCRIPTION
**Pull request by olegsych**
Document Web, DependencyCollector and PerfCounterCollector components for the 1.0 release of the .NET SDK.

The actual doc is here: https://azure.microsoft.com/en-us/documentation/articles/app-insights-configuration-with-applicationinsights-config

### CODE REVIEW

**Comment by olegsych** [comment]
@AlexBulankou, @abaranch, @rinatkar, @alancameronwills, could you take a look?

**Comment by tokaplan** [comment]
The part about perfcollector has this:

The `PerformanceCollectorModule` tracks a number of Windows performance counters. You can see these 
+counters when you open the Filters blade in Metric Explorer

**Comment by alancameronwills** [comment]
Great, Oleg, thanks!

@tokaplan : Open metric explorer. Click "Filters". You get a blade headed "Filter".

**Comment by tokaplan** [comment]
But that's not where you see the counters, right? You see them if you click a chart - that blade is called "Chart details".

**Comment by alancameronwills** [comment]
Ahchhh - yes, of course. Well caught. Let's fix that.

**Comment by olegsych** [comment]
OK. I merged my pull request. @tokaplan & @alancameronwills, will one of you be updating the performance collector section?

**Comment by tokaplan** [comment]
@alancameronwills, will you be doing the change? Or should I do it?

**Comment by alancameronwills** [comment]
Oleg, I put a fix for this in a PR to your branch - correct?
Normally I work with azure-content-pr.

**Comment by olegsych** [comment]
@alancameronwills, Using the `app-insights-.net-sdk-1.0` branch in this fork was just a suggestion. If there is another way you prefer that we can use to collect these changes together and hold off publishing them until 1.0 is released, I'm all for it :smile:

**Comment by alancameronwills** [comment]
OK.

**Pull request merged**
